### ISSUE TITLE
I had some errors compiling vixi-master

### ISSUE THREAD

**Issue by gitQqqHs** [Peltoche/vixi#10]
error[E0433]: failed to resolve: maybe a missing `extern crate sys;`?
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\lib.rs:22:9
   |
22 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing `extern crate sys;`?

error[E0433]: failed to resolve: maybe a missing `extern crate sys;`?
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\lib.rs:23:9
   |
23 | pub use sys::tty::{is_tty, get_tty};
   |         ^^^ maybe a missing `extern crate sys;`?

error[E0433]: failed to resolve: maybe a missing `extern crate sys;`?
 --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\async.rs:5:5
  |
5 | use sys::tty::get_tty;
  |     ^^^ maybe a missing `extern crate sys;`?

error[E0433]: failed to resolve: maybe a missing `extern crate sys;`?
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\raw.rs:29:5
   |
29 | use sys::attr::{get_terminal_attr, raw_terminal_attr, set_terminal_attr};
   |     ^^^ maybe a missing `extern crate sys;`?

error[E0432]: unresolved import `sys`
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\raw.rs:28:5
   |
28 | use sys::Termios;
   |     ^^^ maybe a missing `extern crate sys;`?

   Compiling bincode v1.1.3
   Compiling toml v0.4.10
error[E0425]: cannot find function `get_tty` in this scope
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\async.rs:20:36
   |
20 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\raw.rs:45:9
   |
45 |         set_terminal_attr(&self.prev_ios).unwrap();
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\raw.rs:90:23
   |
90 |         let mut ios = get_terminal_attr()?;
   |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\raw.rs:93:9
   |
93 |         raw_terminal_attr(&mut ios);
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
  --> C:\Users\rog\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src\raw.rs:95:9
   |
95 |         set_terminal_attr(&ios)?;
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

   Compiling toml v0.5.0
   Compiling syn v0.15.30
error: aborting due to 10 previous errors

Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.
error: Could not compile `termion`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by gitQqqHs** [comment]
I got the above error when I compiled vixi using the latest rust

**Comment by wezm** [comment]
It appears you're on Windows. `vixi` uses [termion](https://gitlab.redox-os.org/redox-os/termion), which unfortunately doesn't support Windows:

> Supports Redox, Mac OS X, BSD, and Linux (or, in general, ANSI terminals).

**Comment by Peltoche** [comment]
Maybe one day an integration with windows will be done, the architecture allows it but at the moment it's not really the priority.

**Comment by nico-abram** [comment]
The windows mention in https://github.com/Peltoche/vixi#configuration seems a bit misleading if windows isn't currently supported

**Comment by Peltoche** [comment]
I will remove it. Thanks for the issue :+1
