### ISSUE TITLE
Consider Kakoune mode

### ISSUE THREAD

**Issue by heyakyra** [Peltoche/vixi#18]
quoting @zellyn : https://github.com/xi-editor/xi-editor/issues/337

> Not only is Kakoune an interesting and ambitious redesign of a modal editing UI, but many of the features, such as multiple selections and especially selection splitting, would be an interesting test case for Xi: if you can cover Kakoune functionality, you should be able to cover anything!

**Comment by Peltoche** [comment]
Hi, this project is kind of terminated. I hope that someone will create a fork a implement the awesome feature.
